apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: weekly-report
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: weekly-report-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
