apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weeklyreport-dev-uploads
  namespace: weeklyreport-dev
  labels:
    app: weeklyreport-dev
spec:
  storageClassName: huawei-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
